상품 등록(사전 등록, 경매 등록, 사전->경매 전환) 구현
CHZZK-Study/Chzz-Market-Backend pull request #20
Opened 2024-08-07 21:48 UTC by viaunixue

## #️⃣연관된 이슈

CHZZ-35 #35 #done

## 📝작업 내용

* 상품 등록이 이루어지면 상품 테이블과 경매 테이블에 상품이 등록되고 Enum을 통해 관리됩니다.
경매 테이블에서 사전 등록에 대한 Enum 관리 없이 상품에 대한 유효성 검사가 이루어지도록 구현했습니다.

* ProductStatus Enum을 통해 경매와 별도의 상품 생명 주기를 관리합니다.
    * 사전 등록 단계에 대한 상태 관리와 경매 전환에서의 상품 유효성 검사에 사용됩니다.
    * 현재는 '사전 등록', '경매 등록', '판매 완료', '취소 됨' 상태가 존재합니다.

* 상품을 사전 등록하는 API를 구현하였습니다.
    * 상품 상태 PRE_REGISTERED(사전 등록) 상태로 상품 테이블에 저장됩니다.
    * 경매 상태 PENDING(대기 중) 상태로 경매 테이블에 저장됩니다.

* 상품을 경매 등록하는 API를 구현하였습니다.
    * 상품 상태 IN_AUCTION(경매 중) 상태로 상품 테이블에 저장됩니다.
    * 경매 상태 PROCEEDING(진행 중) 상태로 경매 테이블에 저장됩니다.

* 사전 등록 상품을 경매 상품으로 전환하는 API를 구현하였습니다.
    * 상품 유효성 검사 이후 Product와 Auction의 상태를 업데이트 합니다.

* 사전 등록과 경매 등록에서 이미지 처리는 트랜잭션 외부에서 진행됩니다.

* 이미지 업로드, 엔티티 저장, 삭제, URL 관리 용도로 메소드를 분리했습니다.

## ✅테스트 결과

> 상품 등록 Controller 테스트
 
![image](https://github.com/user-attachments/assets/b263de6d-c4ed-4ce8-b609-d9a263c2a930)

> 상품 등록 Service 테스트

![image](https://github.com/user-attachments/assets/10132228-0d00-4e97-ad20-4a1ef691d8af)

## 🙏리뷰 요구사항(선택)

2024-08-08 07:08 UTC, YeaChan05 requested changes

2024-08-08 07:08 UTC, YeaChan05 commented on src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
> +        }
검증 로직인 만큼 도메인에 역할을 위임해도 좋을거 같습니다

2024-08-08 07:08 UTC, YeaChan05 commented on src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
> +        auctionRepository.save(auction);
`@Transactional`이 필요하지 않을까요?

2024-08-08 07:09 UTC, YeaChan05 commented on src/main/java/org/chzz/market/domain/image/service/ImageService.java
> +                .collect(Collectors.toList());
`toList()`로 축약 가능해 보입니다

2024-08-08 07:11 UTC, junest66 commented on src/main/java/org/chzz/market/domain/product/service/ProductService.java
> +            auctionService.proceedingAuctionForProduct(product);
함수에 AuctionStatus 를 같이 넘기면 하나의 함수에서 처리가 가능하지 않을까요?

2024-08-08 07:11 UTC, junest66 commented on src/main/java/org/chzz/market/domain/product/service/ProductService.java
> +    private Product createProduct(RegisterProductRequest request, User user, ProductStatus status) {
해당 함수는  RegisterProductRequest 내에서 toEntity() 이런 함수로 만들면 get 메서드로 안꺼내고 Entity 객체를 만들 수 있지 않을까요?

2024-08-08 07:11 UTC, junest66 commented on src/main/java/org/chzz/market/domain/product/service/ProductService.java
> +    public RegisterProductResponse convertToAuctionWithPossibleFailure(Long productId, boolean shouldFail) {
product 코드에는 테스트만을 위해 코드를 작성하는건 좋지 않은 것 같습니다!

2024-08-08 07:11 UTC, junest66 commented on src/main/java/org/chzz/market/domain/image/service/ImageService.java
>              imageRepository.save(imageEntity);
현재 삽입쿼리가 cdnPaths 만큼 호출 될 것 같은데 saveAll() 함수를 쓰면 하나의 쿼리에서 삽입 가능하지 않을까요??

2024-08-08 07:11 UTC, YeaChan05 commented on src/main/java/org/chzz/market/domain/image/service/ImageService.java
`uploadImage`를 할때 한번에 여러개의 이미지를 올리는 방식과 하나씩 여러번 올리는 방식중에 어느쪽이 오버헤드가 덜한가요?

제 경험상으로 데이터 전송시에는 bulk 방식이 일반적으로 더 효율적인거로 알고 있는데 이미지는 어떨지 잘 모르겠네요

2024-08-08 07:57 UTC, YeaChan05 commented on src/main/java/org/chzz/market/domain/product/controller/ProductController.java
> +    public ResponseEntity<RegisterProductResponse> preRegisterProduct(@ModelAttribute @Valid RegisterProductRequest request) {
`@RequsetBody`를 사용 안핫신 이유가 있을까요?

2024-08-08 08:15 UTC, YeaChan05 commented on src/main/java/org/chzz/market/domain/product/controller/ProductController.java
그래서 개인적으로 저는 별도의 컨트롤러에서 등록을 담당해주는편이 좋다고 생각합니다
사실 둘이 어느정도 중복되는 느낌도 있고 해서 요청 타입에 따른 컴포넌트를 잘 전달 할 수 있도록 추상화된 서비스를 만들어 두면 개발 난이도도 떨어지고 도메인 분리도 확실하다고 생각됩니다
아래 래은님 PR에도 남겼던 글이 있는데 확인해보시면 좋을거 같아요
https://github.com/CHZZK-Study/Chzz-Market-Backend/pull/16/files#r1706515209

2024-08-08 08:22 UTC, YeaChan05 commented on src/main/java/org/chzz/market/domain/product/service/ProductService.java
> +        }
별도의 예외를 로직에서 처리해두신 이유가 있을까요?

2024-08-08 09:07 UTC, YeaChan05 commented
서비스 로직에서 예외처리를 한부분이 꽤 있어보입니다
예외상황을 처리하는 경우 대부분 `GlobalExceptionHandler`가 처리하고, 일부 예외 상황에 로직이 필요한 경우에는 retry&recover로 복구하는것이 SRP에 맞다고 생각됩니다

2024-08-08 09:07 UTC, YeaChan05 commented
그리고 등록이라는 엔드포인트 자체를 하나로 두고 이를 사용자의 요청에 따라 추상화된 서비스를 호출하는 방식에 대해 고민해보셔도 좋을거 같습니다

2024-08-10 05:44 UTC, viaunixue commented
간단하게 경매 등록, 사전 등록 수정하여 초기 구현 해보았습니다. 해당 리뷰 이후 문제없으면 계속 진행하겠습니다!

2024-08-10 09:09 UTC, YeaChan05 commented on src/main/java/org/chzz/market/domain/auction/controller/RegisterController.java
> +    public ResponseEntity<RegisterResponse> registerAuctionProduct(@ModelAttribute @Valid RegisterRequest request) {
`@RequestBody`가 아닌 `@ ModelAttribute`를 사용하신 이유가 있을까요?

2024-08-10 10:50 UTC, junest66 commented on src/main/java/org/chzz/market/domain/auction/controller/RegisterController.java
> +@RequestMapping("/register")
경매 등록과 사전 등록이 동일한 `RegisterRequest` DTO를 사용하고 있다면, 이 두 가지 기능을 하나의 엔드포인트에서 처리하는 것 도 한번 생각해보면 어떨까요? 또한 RESTful API 설계에 따라, 두 가지 등록이 모두 경매와 관련된 리소스에 대한 작업이므로, `POST /auctions`과 같은 엔드포인트에서 상태에 따라 구분하여 처리하는 방식은 어떻게 생각하시나요?

2024-08-10 10:50 UTC, junest66 commented on src/main/java/org/chzz/market/domain/auction/controller/RegisterController.java
> +@RequestMapping("/register")
요청 DTO에 경매 상태(`AuctionStatus`) 필드를 추가해서 하나의 엔드포인트에서 두개의 함수로 나눠서 처리하는 방법도 있을것 같은데 어떻게 생각하시나요?

2024-08-10 10:54 UTC, junest66 commented on src/main/java/org/chzz/market/domain/auction/controller/RegisterController.java
> +@RequestMapping("/register")
아니면 각각 `POST api/v1/auctions/` `POST api/v1/pre-auctions/` 해야 restful api 설계에 부합하지않을까요 `register/auctions` 는 설계원칙과는 맞지 않는다고는 생각합니다

2024-08-10 15:28 UTC, YeaChan05 commented on src/main/java/org/chzz/market/domain/auction/controller/RegisterController.java
> +@RequestMapping("/register")
> 요청 DTO에 경매 상태(`AuctionStatus`) 필드를 추가해서 하나의 엔드포인트에서 두개의 함수로 나눠서 처리하는 방법도 있을것 같은데 어떻게 생각하시나요?

개인적으로 이 방향이 더 가성비(?)가 좋지 않나 싶습니다

2024-08-11 05:53 UTC, junest66 commented on src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
> +        Auction savedAuction = auctionRepository.save(auction);
해당 코드는 jpa 변경감지 기능으로 인해 호출이 불필요할것 같습니다!

2024-08-11 05:53 UTC, junest66 commented on src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
> +    private Auction createAuction(Product product, RegisterRequest request, AuctionStatus status) {
경매등록이면 경매종료 컬럼을 등록해야하지 않나요? 사전등록이면 해당 컬럼을 null 로 두는게 맞을것 같은데 해당 코드부분이 어디 있나요??

2024-08-11 05:53 UTC, junest66 commented on src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
> +    @PostMapping(value = "/register",
- **`POST /auctions`**: 새로운 경매 상품을 등록하는 작업을 의미합니다.
-  `/register`와 같은 추가적인 경로는 불필요하며, 기본적으로 `POST` 메서드 자체가 리소스 생성을 의미하기 때문에 더 간결하고 직관적인 API 설계를 할 수 있습니다.
- 하지만 경매 상품으로 전환같이 명확한 동작을 명시해야할때는 url에 명시하는게 좋을것같습니다!
-  기본적인 CRUD 작업은 http method로 충분히 나타낼수있을것같습니다!

2024-08-11 07:35 UTC, YeaChan05 commented on src/main/java/org/chzz/market/domain/auction/dto/StartResponse.java
클래스명이 구체적이지 않아 보입니다
무엇을 시작하는지 명시하기 위해 `SuccessfulAucutionStartResponse`로 변경하는건 어떨까요?

2024-08-11 07:41 UTC, YeaChan05 commented on src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
> +        }
동등성 비교만으로 충분하지 않을까요?

2024-08-12 10:51 UTC, didfodms approved these changes
코드 작성하시느라 수고 많으셨습니다 :)
이미지 처리 같은 경우, 저도 잘 모르지만 찾아보니 이렇다고 하네요,,!

> 1. 사용자가 업로드한 이미지를 서버나 클라우드에 저장
> 2. 이미지가 성공적으로 업로드되면 해당 이미지의 경로를 데이터베이스에 저장
> 3. 상품에 대한 나머지 정보를 데이터베이스에 저장

이렇게 처리할 경우, 만약 이미지 업로드에 실패하더라도, 상품 정보 자체는 안전하게 데이터베이스에 저장될 수 있다고 합니다..!

2024-08-12 10:51 UTC, didfodms commented on src/main/java/org/chzz/market/common/config/SecurityConfig.java
로그인(인증)하면 자동대로 auction 페이지로 이동하는 코드가 맞을까요?

2024-08-12 10:51 UTC, didfodms commented on src/main/java/org/chzz/market/domain/user/error/UserErrorCode.java
제가 구현한 로그인 구현 코드에서 JsonProcessingException을 내부에서 처리해야 한다는 피드백을 받았는데요..!
해당 코드를 사용하면 되는지 궁금합니다!
![image](https://github.com/user-attachments/assets/51f89952-80c4-4b98-8c02-104c1fe07030)

2024-08-13 05:20 UTC, junest66 commented on src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
> +        private static class AuctionTypeInjector {
해당 코드는 어떤 동작을 하는건가요??

2024-08-13 05:20 UTC, junest66 commented on src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
> +    public StartAuctionResponse startAuction(StartAuctionRequest request) {
추후에 제품을 올린 userId와 login한 userId 와 동일한지 검증을 추가하는건가요?

2024-08-16 10:32 UTC, junest66 approved these changes

2024-08-17 14:28 UTC, junest66 commented on src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
> +    public StartAuctionResponse startAuction(StartAuctionRequest request) {
해당 사전제품을 올린 user와 요청을 한 user와의 검증은 필수아닌가요??

2024-08-17 14:43 UTC, viaunixue commented on src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
> +    public StartAuctionResponse startAuction(StartAuctionRequest request) {
이 부분 이전 코드라 현재 코드와 다른 상태이긴 한데 말씀하신데로 이 부분 상품 유효성 검사와  동시에 사용자 검증 추가도 필요하겠네요. 수정해보겠습니다! (( 현재 경매 등록 쪽 수정을 사전 등록 상품 수정 PR에서 진행하고 있습니다. 분기된 PR이 많아져서 수정 사항은 해당 PR에서 확인해보실 수 있도록 작업 진행하겠습니다ㅠ ))

2024-08-17 15:02 UTC, YeaChan05 commented on src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
> +    protected Long userId;
요청값으로 사용자의 pk를 받는다는 뜻일까요?
사용자정보는 토큰으로 전달 받을거 같은데요

2024-08-17 15:03 UTC, YeaChan05 commented on src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
> +    public abstract void validate();
구현체가 사용되지 않는거 같은데 추상 메서드를 작성하신 이유가 무엇일까요?

2024-08-17 15:04 UTC, YeaChan05 commented on src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
> +
해당 service injector가 요청 DTO 내부 클래스로 작성하신 이유가 있을까요?

2024-08-17 15:06 UTC, YeaChan05 commented on src/main/java/org/chzz/market/domain/auction/dto/request/RegisterAuctionRequest.java
경매 등록시에는 경매 시작일을 기입해 주어야 할거 같습니다

2024-08-17 15:23 UTC, YeaChan05 commented on src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
> +                    logger.info("유저 ID {}번에 해당하는 유저를 찾을 수 없습니다.", request.getUserId());
에러 로그가 중복된거 같습니다

2024-08-17 15:26 UTC, YeaChan05 commented on src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
> +        User user = userRepository.findById(request.getUserId())
조회성분 쿼리가 발생될거 같은데 트랜잭션을 분리하는게 좋지 않을까요?

2024-08-17 15:33 UTC, YeaChan05 commented on src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
이거 결국에는 서비스 추상화가 안된거 아닌가요?

2024-08-17 16:11 UTC, YeaChan05 commented on src/main/resources/application-local.yml
> +#
이부분은 왜 주석처리 하신건가요?

2024-08-17 16:34 UTC, viaunixue commented on src/main/resources/application-local.yml
> +#
gitignore 설정 당시 인지하지 못하고 push 한 코드가 유지되고 있는 것 같습니다. 수정하면 될 것 같습니다!@

2024-08-17 16:35 UTC, viaunixue commented on src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
AuctionPolicy 추상클래스에서 PreRegisterAuctionPolicy, RegisterAuctionPolicy 클래스를 관리하도록 구현한 부분이 서비스 추상화 아닐까요? 이 부분도 상품 수정 PR에서 수정된 부분 확인 부탁드립니다!

2024-08-17 16:35 UTC, viaunixue commented on src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
> +        User user = userRepository.findById(request.getUserId())
상품 수정 PR에서 수정된 부분 확인 부탁드려요

2024-08-17 16:35 UTC, viaunixue commented on src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
> +                    logger.info("유저 ID {}번에 해당하는 유저를 찾을 수 없습니다.", request.getUserId());
이 부분 상품 수정 PR에 중복 로그 삭제 처리 반영해두었습니다!

2024-08-17 16:35 UTC, viaunixue commented on src/main/java/org/chzz/market/domain/auction/dto/request/RegisterAuctionRequest.java
RegisterAuctionPolicy 클래스에서 생성해주도록 구현하였습니다.!

2024-08-17 16:35 UTC, viaunixue commented on src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
> +
AuctionType과 관련된 모든 로직을 한 곳에서 관리하기 위한 의도였고 응집도를 높일 수 있다고 생각했습니다. request 클래스에 적절하지 않은 구현일까요?

2024-08-17 16:35 UTC, viaunixue commented on src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
> +    public abstract void validate();
만들고 나니 @Valid로 유효성 검사가 진행되어 빈 메서드가 되었는데 향후 @Valid로 처리하기 어려운 복잡한 유효성 검사가 필요할 경우를 대비해 남겨두었던거 같은데 생각해보니 절대 사용 안될 것 같네요. 필요하지 않은 메서드같으니 삭제해두겠습니다!

2024-08-17 16:35 UTC, viaunixue commented on src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
> +    protected Long userId;
현재 저희 시스템에 인증 메커니즘이 완전히 구현되지 않은 상태라 테스트를 위해 임시적인 조치로 userId를 받도록 구현해두었습니다. 향후 인증 시스템이 구현되면 토큰 기반 인증으로 전환할 계획입니다.

2024-08-19 05:57 UTC, YeaChan05 commented on src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
결국 서비스클래스가 하나만 사용되고 있던데요? 그럼 결국 이전과 동일한 코드로 보이는데요

서비스 클래스 추상화를 말씀드린 이유는 반복된 작업을 최소화 하고 각 클래스가 SRP를 지키도록 하기 위함인데 지금 구조면 서비스클래스 하나가 두 도메인로직을 같이 처리하게 되는거 같네요

2024-08-19 05:58 UTC, YeaChan05 commented on src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
> +
bean 주입의 경우 서비스 클래스의 관리와 연관되어 있으니 DTO 내부에는 있을 이유가 없을거 같네요

2024-08-19 05:59 UTC, YeaChan05 commented on src/main/java/org/chzz/market/domain/auction/dto/request/RegisterAuctionRequest.java
이렇게되면 DTO 추상화의 의미가 없지 않나요? 의도와 전혀 관련없는 코드가 작성된거 같은데요

2024-08-19 07:06 UTC, viaunixue commented on src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
말씀해주신 리뷰 토대로 상품 수정 PR에 리팩토링 한번 해보았습니다. 이 방식이 올바르다면 테스트 코드까지 수정하여 코드 수정 마무리해보겠습니다!

2024-08-20 15:01 UTC, didfodms approved these changes
확인했습니다 :) 수고 많으셨습니다

2024-08-20 15:05 UTC, YeaChan05 approved these changes

2024-08-20 15:09 UTC, merged